experiment_name:                    
use_gpu:                            True
gpu_id:                             0                    
seed:                               0

network_simulation: True
ode_simulation: False

ode_run:
  implementation:                   python
  timestep:                         0.01

task:
  label_task_boundaries:            True                      
  learner_configuration:            continual                 # meta or continual - specifies whether student has separate heads for each teacher (continual) or not (meta)
  teacher_configuration:            both_rotation               # feature_rotation, readout_rotation,, noisy, independent, overlapping, drifting, trained_mnist (see README)
  num_teachers:                     2                         
  loss_type:                        regression                # classification or regression

training:
  total_training_steps:             3000000
  train_batch_size:                 1                         
  learning_rate:                    5                                             
  loss_function:                    mse                       # mse, bce
  scale_head_lr:                    False                      # whether to add 1/N factor in lr of output layer  
  scale_hidden_lr:                  False                      # whether to add 1/\sqrt{N} factor in forward of hidden layer(s)
  # scale_forward_by_hidden:          True                      # whether to scale forward of network by 1/K (hidden dim)--for mean-field regime
  train_hidden_layers:              True
  train_head_layer:                 True
  freeze_features:                  []                      # hidden layers frozen / unfrozen at these steps.

data:
  input_source:                     iid_gaussian              # iid_gaussian, mnist_stream, mnist_digits, even_greater (see README)

  iid_gaussian:
    mean:                           0
    variance:                       1
    dataset_size:                   inf

logging:
  verbose:                          True                      
  verbose_tb:                       0                         # 0 - no tb logging, 1 - minimal tb logging, 2 - full tb logging                     
  log_frequency:                    100
  checkpoint_frequency:             1000                      
  log_to_df:                        True
  merge_at_checkpoint:              True
  save_weights_at_switch:           True
  save_weight_frequency:            500
  save_initial_weights:             True
  save_teacher_weights:             True
  log_overlaps:                     False
  split_logging:                    False
  
testing:
  test_batch_size:                  50000                     # generalisation error
  test_frequency:                   100                         # how often during training to perform generalisation error test loop
  overlap_frequency:                100                       # how often during training to compute / visualise overlap matrices

model:
  input_dimension:                  15                 
  output_dimension:                 1

  student:
    teacher_features_copy:                                      # emtpy/None = indpendent of teachers, integer = index of teacher to copy
    student_hidden_layers:            [1000]                       
    student_nonlinearity:             scaled_erf                      
    apply_nonlinearity_on_output:     False
    student_initialisation_std:       0.001                     # std of normal initialisation for student network
    initialise_student_outputs:       True                      # whether or not to initialise hidden -> output weights of student
    soft_committee:                   False                     # whether or not to fix output layer of student to 1 (scm)
    student_bias_parameters:          False                     # whether or not to have bias parameters on linaer layers (student)
    symmetric_student_initialisation: False                     # identically initialised student hidden units
    scale_student_forward_by_hidden:  True

  teachers:
    teacher_hidden_layers:            [250]                                                
    teacher_nonlinearities:           [scaled_erf, scaled_erf]              # per teacher
    normalise_teachers:               True
    teacher_initialisation_std:       1                         # std of normal initialisation for teacher network
    unit_norm_teacher_head:           False                      # choose head weight from 1, -1 or initialise using normal
    teacher_bias_parameters:          False                     # whether or not to have bias parameters on linaer layers (teacher)
    teacher_noises:                   [0, 0]
    scale_teacher_forward_by_hidden:  True
    feature_rotation:
      rotation_magnitude:             1.5708
    readout_rotation:
      rotation_magnitude:             3.14159
      feature_copy_percentage:        100
    both_rotation:
      feature_rotation_alpha:         0.5
      readout_rotation_alpha:         0.1
    

curriculum:
  stopping_condition:               switch_steps              # condition on which to switch task (fixed_period, switch_steps, or threshold)
  switch_steps:                     [1500000]
  fixed_period:                     2500                      # period for changing tasks 
  loss_thresholds:                  [0.0001, 0.0001, 0.00001, 0.000001, 0.0000001, 0.00000001, 0.000000001, 0.0000000001]                    # loss threshold under which teacher is changed
